#!/usr/bin/env python3
# Code generated by Codex (GPT-5) in response to user prompt:
# "Write multiple scripts that will take the different University cataog files in the data folder as an input and then output the data within those files into a new json file with the following schema..."

from __future__ import annotations

from typing import Any, Dict

from catalog_common import (
    build_arg_parser,
    clean_text,
    extract_coreq_statements,
    extract_course_ids,
    extract_noteworthy_sentences,
    extract_prereq_statements,
    infer_course_id,
    load_json,
    normalize_path,
    write_json,
)

DEFAULT_INPUT = "data/mit_courses.json"
DEFAULT_OUTPUT = "data/MIT_coursecatalogstructured.json"


def transform_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    course_name = clean_text(entry.get("Course Name"))
    course_id = infer_course_id(course_name)
    description = clean_text(entry.get("courseBlockDescrption"))
    prereq_source = entry.get("courseBlockPreReq")

    prereq_statements = extract_prereq_statements(prereq_source, description)
    coreq_statements = extract_coreq_statements(prereq_source, description)
    prereq_texts = (
        prereq_statements
        if prereq_statements
        else ([prereq_source] if prereq_source else [])
    )
    coreq_texts = coreq_statements
    prereqs = extract_course_ids(*prereq_texts)
    coreqs = extract_course_ids(*coreq_texts)
    notes = extract_noteworthy_sentences(description)

    other = {}
    course_hours = clean_text(entry.get("Course Hours"))
    if course_hours:
        other["course_hours"] = course_hours
    if notes:
        other["notes"] = notes

    structured = {
        "coursename": course_name or None,
        "courseid": course_id or None,
        "coursedescription": description or None,
        "course-prerequsities": prereqs,
        "course-corequisites": coreqs,
        "other": other or None,
    }
    return structured


def main() -> None:
    parser = build_arg_parser(DEFAULT_INPUT, DEFAULT_OUTPUT)
    args = parser.parse_args()
    input_path = normalize_path(args.input)
    output_path = normalize_path(args.output)

    raw_data = load_json(input_path)
    if not isinstance(raw_data, list):
        raise ValueError("MIT catalog input must be a list of courses.")

    structured = [transform_entry(entry) for entry in raw_data]
    write_json(output_path, structured)
    print(f"Processed {len(structured)} MIT courses -> {output_path}")


if __name__ == "__main__":
    main()
