#!/usr/bin/env python3
# Code generated by Codex (GPT-5) in response to user prompt:
# "Write multiple scripts that will take the different University cataog files in the data folder as an input and then output the data within those files into a new json file with the following schema..."

from __future__ import annotations

from typing import Any, Dict

from catalog_common import (
    build_arg_parser,
    clean_text,
    extract_coreq_statements,
    extract_course_ids,
    extract_noteworthy_sentences,
    extract_prereq_statements,
    infer_course_id,
    load_json,
    normalize_path,
    write_json,
)

DEFAULT_INPUT = "data/nyu_courses.json"
DEFAULT_OUTPUT = "data/NYU_coursecatalogstructured.json"


def transform_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    course_name = clean_text(entry.get("Class Title"))
    course_id = clean_text(entry.get("Class Code")) or infer_course_id(course_name)
    description = clean_text(entry.get("Class Description"))

    prereq_source = entry.get("Class Prerequisites")
    prereq_statements = extract_prereq_statements(
        prereq_source,
        description,
    )
    coreq_statements = extract_coreq_statements(
        prereq_source,
        description,
    )
    prereq_texts = (
        prereq_statements
        if prereq_statements
        else ([prereq_source] if prereq_source else [])
    )
    prereqs = extract_course_ids(*prereq_texts)
    coreqs = extract_course_ids(*coreq_statements)

    other = {}
    credits = clean_text(entry.get("Class Credits"))
    grading = clean_text(entry.get("Class Grading"))
    repeatable = clean_text(entry.get("Class Repeatable"))
    antireq = clean_text(entry.get("Class Antirequisities"))
    notes = extract_noteworthy_sentences(description)

    if credits:
        other["credits"] = credits
    if grading:
        other["grading"] = grading
    if repeatable:
        other["repeatable"] = repeatable
    if antireq:
        other["antirequisites"] = antireq
    if notes:
        other["notes"] = notes

    return {
        "coursename": course_name or None,
        "courseid": course_id or None,
        "coursedescription": description or None,
        "course-prerequsities": prereqs,
        "course-corequisites": coreqs,
        "other": other or None,
    }


def main() -> None:
    parser = build_arg_parser(DEFAULT_INPUT, DEFAULT_OUTPUT)
    args = parser.parse_args()
    input_path = normalize_path(args.input)
    output_path = normalize_path(args.output)

    raw_data = load_json(input_path)
    if not isinstance(raw_data, list):
        raise ValueError("NYU catalog input must be a list of courses.")

    structured = [transform_entry(entry) for entry in raw_data]
    write_json(output_path, structured)
    print(f"Processed {len(structured)} NYU courses -> {output_path}")


if __name__ == "__main__":
    main()
