#!/usr/bin/env python3
# Code generated by Codex (GPT-5) in response to user prompt:
# "Write multiple scripts that will take the different University cataog files in the data folder as an input and then output the data within those files into a new json file with the following schema..."

from __future__ import annotations

from typing import Any, Dict

from catalog_common import (
    build_arg_parser,
    clean_text,
    extract_coreq_statements,
    extract_course_ids,
    extract_noteworthy_sentences,
    extract_prereq_statements,
    load_json,
    normalize_path,
    write_json,
)

DEFAULT_INPUT = "data/course-catalog-scraper-2025-10-24.json"
DEFAULT_OUTPUT = "data/UMASS_BOSTON_coursecatalogstructured.json"


def transform_entry(course_id: str, data: Dict[str, Any]) -> Dict[str, Any]:
    descriptors = data.get("course_descriptors") or {}
    description = clean_text(descriptors.get("description"))
    prereq_field = descriptors.get("pre requisites")

    prereq_statements = extract_prereq_statements(prereq_field, description)
    coreq_statements = extract_coreq_statements(prereq_field, description)
    prereq_texts = (
        prereq_statements
        if prereq_statements
        else ([prereq_field] if prereq_field else [])
    )
    prereqs = extract_course_ids(*prereq_texts)
    coreqs = extract_course_ids(*coreq_statements)
    notes = extract_noteworthy_sentences(description)

    descriptor_extras = {
        key: clean_text(value)
        for key, value in descriptors.items()
        if key not in {"description", "pre requisites"} and clean_text(value)
    }

    other = {}
    if descriptor_extras:
        other["descriptors"] = descriptor_extras
    if notes:
        other["notes"] = notes

    return {
        "coursename": clean_text(data.get("title")) or None,
        "courseid": clean_text(data.get("id") or course_id) or None,
        "coursedescription": description or None,
        "course-prerequsities": prereqs,
        "course-corequisites": coreqs,
        "other": other or None,
    }


def main() -> None:
    parser = build_arg_parser(DEFAULT_INPUT, DEFAULT_OUTPUT)
    args = parser.parse_args()
    input_path = normalize_path(args.input)
    output_path = normalize_path(args.output)

    raw_data = load_json(input_path)
    if not isinstance(raw_data, dict):
        raise ValueError("UMass catalog input must be a dictionary of courses.")

    structured = [
        transform_entry(course_id, payload) for course_id, payload in raw_data.items()
    ]
    write_json(output_path, structured)
    print(f"Processed {len(structured)} UMass Boston courses -> {output_path}")


if __name__ == "__main__":
    main()
