#!/usr/bin/env python3
# Code generated by Codex (GPT-5) in response to user prompt:
# "Write multiple scripts that will take the different University cataog files in the data folder as an input and then output the data within those files into a new json file with the following schema..."

from __future__ import annotations

from typing import Any, Dict

from catalog_common import (
    build_arg_parser,
    clean_text,
    extract_coreq_statements,
    extract_course_ids,
    extract_noteworthy_sentences,
    extract_prereq_statements,
    infer_course_id,
    load_json,
    normalize_path,
    write_json,
)

DEFAULT_INPUT = "data/upenn_courses.json"
DEFAULT_OUTPUT = "data/UPENN_coursecatalogstructured.json"


def transform_entry(entry: Dict[str, Any]) -> Dict[str, Any]:
    course_name = clean_text(entry.get("Course Name"))
    course_id = infer_course_id(course_name)
    description = clean_text(entry.get("Course Descrition"))

    prereq_statements = extract_prereq_statements(description)
    coreq_statements = extract_coreq_statements(description)
    prereqs = extract_course_ids(*prereq_statements)
    coreqs = extract_course_ids(*coreq_statements)
    notes = extract_noteworthy_sentences(description)

    other = {}
    credits = clean_text(entry.get("Course Credits"))
    if credits:
        other["credits"] = credits
    if notes:
        other["notes"] = notes

    return {
        "coursename": course_name or None,
        "courseid": course_id or None,
        "coursedescription": description or None,
        "course-prerequsities": prereqs,
        "course-corequisites": coreqs,
        "other": other or None,
    }


def main() -> None:
    parser = build_arg_parser(DEFAULT_INPUT, DEFAULT_OUTPUT)
    args = parser.parse_args()
    input_path = normalize_path(args.input)
    output_path = normalize_path(args.output)

    raw_data = load_json(input_path)
    if not isinstance(raw_data, list):
        raise ValueError("UPenn catalog input must be a list of courses.")

    structured = [transform_entry(entry) for entry in raw_data]
    write_json(output_path, structured)
    print(f"Processed {len(structured)} UPenn courses -> {output_path}")


if __name__ == "__main__":
    main()
